import type { Effect, BloodMoonEffect, EffectType } from './Effect';

export enum CardType {
  // Basic Types
  WARRIOR = 'WARRIOR',
  MAGE = 'MAGE',
  ASSASSIN = 'ASSASSIN',
  BEAST = 'BEAST',
  
  // Additional Types
  DEMON = 'DEMON',
  ANGEL = 'ANGEL',
  ELEMENTAL = 'ELEMENTAL',
  NECROMANCER = 'NECROMANCER',
  DRAGON = 'DRAGON',
  MECHANICAL = 'MECHANICAL',
  SPIRIT = 'SPIRIT',
  UNDEAD = 'UNDEAD',
  CELESTIAL = 'CELESTIAL',
  ABYSSAL = 'ABYSSAL',

  // Dark Fantasy Types
  VOID = 'VOID',
  BLOOD = 'BLOOD',
  NETHER = 'NETHER'
}

export enum CardRarity {
  COMMON = 'COMMON',
  RARE = 'RARE',
  EPIC = 'EPIC',
  LEGENDARY = 'LEGENDARY',
  MYTHIC = 'MYTHIC'
}

export enum Phase {
  Normal = 'normal',
  BloodMoon = 'bloodMoon',
  Void = 'void'
}

export interface CardStats {
  attack: number;
  health: number;
  bloodMoonEnergy?: number; // Energy generated when card is played
  phaseEffects: {
    [key in Phase]?: {
      attackBonus?: number;
      healthBonus?: number;
      energyBonus?: number; // Additional energy in specific phase
      specialEffect?: string;
      transformInto?: CardType;
      voidEffect?: {
        magicEffect?: string;
        targetable?: boolean;
        powerTransfer?: number;
        voidAbility?: string;
      };
    }
  };
  bloodMoonCost?: number;  // Only used during blood moon phases
}

export interface Card {
  id: string;
  id_name: string;
  name: string;
  type: CardType;
  rarity: CardRarity;
  stats: CardStats;
  effects: Effect[];
  bloodMoonEffects?: BloodMoonEffect[];
  description: string;
  flavorText?: string;
  
  // Current state properties
  currentAttack: number;
  currentHealth: number;
  currentBloodMoonEnergy?: number; // Current energy value, which can be modified
  isTransformed: boolean;
  currentPhase?: Phase;  // Track which phase the card was played in
  
  // Card Type Specific Properties
  typeProperties?: {
    [key in CardType]?: {
      specialAbility?: string;
      passiveEffect?: string;
      energyGeneration?: {
        onPlay?: number;
        onAttack?: number;
        onDamageDealt?: number;
        perTurn?: number;
      },
      synergyWith?: CardType[];
      weaknessAgainst?: CardType[];
      phaseBonus?: {
        [key in Phase]?: {
          effect?: string;
          value?: number;
          energyBonus?: number;
        }
      }
    }
  };
  
  // Metadata
  artworkUrl?: string;
  animationUrl?: string;
  soundEffects?: {
    onPlay?: string;
    onAttack?: string;
    onDeath?: string;
    onTransform?: string;
    onPhaseChange?: string;
  };
}

export interface PlayedCard {
  playerId: string;
  cardId: string;
  cardName: string;
  cardDescription: string;
  cardType: CardType;
  cardCost: number;
  cardDamage: number;
  cardHealing: number;
  cardEnergy?: number; // Energy generated by the played card
  turnPlayed: number;
}
